"""Every table and figure, in one command: `make ds` (or `python src/run_all.py`).

  SMARAN_DS_SMALL=1   the cut-down cohort (48 patients, 300 days), the version CI runs
  SMARAN_DS_BOOT=200  fewer bootstrap resamples (the default, 1000, is what the committed results used)
  SMARAN_DS_RESULTS=dir  write somewhere other than results/

Writes results/*.csv, results/figures/*.png (each with a .json sidecar holding the seed and parameters),
results/run_info.json (versions, seed, wall time per step) and results/SUMMARY.md (the headline tables).
"""

from __future__ import annotations

import json
import time

import pandas as pd

import ablations
import clustering
import evaluate_rules
import federated_sim
import practice
import reliability
import sensitivity
import sundowning
from common import N_BOOT, RESULTS, get_cohort, params_from_env, run_info, save_table
from rules import RULE_NAMES

STEPS = [
    ("alert-rule comparison", evaluate_rules.main),
    ("ablations", ablations.main),
    ("reliability", reliability.main),
    ("practice effects", practice.main),
    ("sensitivity to the assumptions", sensitivity.main),
    ("sundowning", sundowning.main),
    ("clustering", clustering.main),
    ("federated learning", federated_sim.main),
]


def cohort_summary(cohort) -> pd.DataFrame:
    p = cohort.patients
    s = cohort.sessions
    per = s.groupby("patient_idx").size()
    rows = []
    for kind, g in p.groupby("trajectory"):
        idx = g.patient_idx
        rows.append({
            "trajectory": kind, "patients": len(g), "sundowners": int(g.sundowner.sum()),
            "sessions_per_patient_median": float(per.reindex(idx).median()),
            "abandoned_share": float(s[s.patient_idx.isin(idx)].abandoned.mean()),
            "stopped_early": int(g.dropout_day.notna().sum()),
        })
    return pd.DataFrame(rows)


def md_table(df: pd.DataFrame, cols: dict, fmt: dict | None = None) -> str:
    fmt = fmt or {}
    head = "| " + " | ".join(cols.values()) + " |\n|" + "---|" * len(cols) + "\n"
    body = ""
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            if isinstance(v, float):
                cells.append("n/a" if pd.isna(v) else fmt.get(c, "{:.2f}").format(v))
            else:
                cells.append(str(v))
        body += "| " + " | ".join(cells) + " |\n"
    return head + body


def ci(df: pd.DataFrame, col: str, pct: bool = True) -> pd.Series:
    scale = 100 if pct else 1
    f = "{:.0f}%" if pct else "{:.1f}"
    return df.apply(lambda r: f"{f.format(r[col] * scale)} ({f.format(r[col + '_lo'] * scale)} to {f.format(r[col + '_hi'] * scale)})", axis=1)


def summary_md() -> str:
    R = RESULTS
    d = pd.read_csv(R / "rules_default_operating_points.csv")
    out = ["# Results at a glance", "",
           "Generated by `python src/run_all.py` from the CSVs beside it. Every number depends on the simulation's "
           "assumptions (README.md); read them there before quoting any of these. Intervals are 95%, from a patient-level "
           f"bootstrap of {N_BOOT} resamples.", ""]
    for level, title in (("watch_or_worse", "As shipped: an alert at 'watch' or worse"), ("decline_only", "Stricter: only a 'decline' alert")):
        t = d[(d.level == level) & (d.gating == "on")].copy()
        t["sens30"], t["sens90"] = ci(t, "sens_30d"), ci(t, "sens_90d")
        t["delay"] = t.apply(lambda r: "n/a" if pd.isna(r.median_delay_days) else f"{r.median_delay_days:.0f}", axis=1)
        t["fa"] = ci(t, "false_alarms_per_patient_year_stable", pct=False)
        out += [f"## Alert rules, {title}", "",
                md_table(t, {"name": "Rule", "sens30": "Detected within 30 days", "sens90": "within 90 days", "delay": "Median delay (days)",
                             "fa": "False alarms per stable patient-year"}), ""]
    m = pd.read_csv(R / "rules_matched_false_alarms.csv")
    m = m[m.false_alarms_per_patient_year_budget.isin([1.0, 2.0, 4.0])].dropna(subset=["threshold"]).copy()
    m["sens90"] = ci(m, "sens_90d")
    m["budget"] = m.false_alarms_per_patient_year_budget.map(lambda x: f"{x:g}")
    out += ["## At the same false-alarm budget (each rule at its most sensitive threshold within it)", "",
            md_table(m, {"budget": "Budget (per patient-year)", "name": "Rule", "sens90": "Detected within 90 days"}), ""]
    low = pd.read_csv(R / "rules_low_scorers.csv")
    low["fa"] = low.apply(lambda r: f"{r.false_alarms_per_patient_year:.1f} ({r.lo:.1f} to {r.hi:.1f})", axis=1)
    out += ["## Stable patients only, by how high they usually score (false alarms per patient-year)", "",
            md_table(low, {"name": "Rule", "stable_patients_scoring": "Her usual level", "fa": "False alarms"}), ""]
    rel = pd.read_csv(R / "reliability.csv")
    rel = rel[rel.scope == "all domains"].copy()
    rel["icc"] = rel.apply(lambda r: f"{r.icc_2_1:.2f} ({r.icc_2_1_lo:.2f} to {r.icc_2_1_hi:.2f})", axis=1)
    out += ["## Test-retest reliability, stable patients, ICC(2,1)", "",
            md_table(rel, {"measure": "Measure", "n_subjects": "Patient-domains", "icc": "ICC"}), ""]
    pm = pd.read_csv(R / "practice_masking.csv")
    pm["slope"] = pm.apply(lambda r: f"{r.points_per_30_days:+.2f} ({r.lo * 30:+.2f} to {r.hi * 30:+.2f})", axis=1)
    out += ["## Practice effects: the trend in an early decliner's scores, points per 30 days", "",
            md_table(pm, {"model": "Model", "slope": "Trend"}), ""]
    sens = pd.read_csv(R / "sensitivity.csv")
    key = [c for c in sens.columns if c.startswith("sens_90d_at_")][0]
    order = sens.pivot(index="variant", columns="rule", values=key)
    held = int((order.idxmax(axis=1) == "R3").sum())
    out += ["## Do the conclusions survive other assumptions?", "",
            f"At the same false-alarm budget CUSUM caught the most in {held} of {len(order)} variants "
            f"(see sensitivity.csv; each variant changes one assumption).", ""]
    cl = pd.read_csv(R / "clustering_summary.csv")
    best = cl.loc[cl.adjusted_rand_index.idxmax()]
    out += ["## Clustering of course shapes (PCA then k-means)", "",
            f"Adjusted Rand index against the true trajectory types: {best.adjusted_rand_index:.2f} at k = {int(best.k)} "
            f"(0 is chance, 1 is perfect).", ""]
    left = pd.read_csv(R / "ablation_left_sessions.csv")
    left = left[left.rule == "R2"].copy()
    left["fa"] = left.apply(lambda r: f"{r.false_alarms_per_patient_year_stable:.1f}", axis=1)
    left["sens"] = ci(left, "sens_90d")
    out += ["## Sessions she left part-way, shown to the two-consecutive rule or not", "",
            md_table(left, {"setting": "Which sessions the engine sees", "sens": "Detected within 90 days", "fa": "False alarms per stable patient-year"}), ""]
    fl = pd.read_csv(R / "fl_summary.csv")
    out += ["## Federated learning: predicting an abandoned session", "",
            md_table(fl, {"method": "Method", "auc": "AUC", "log_loss": "Log-loss", "new_patient_auc": "AUC, new patient",
                          "bytes_on_the_wire": "Bytes on the wire"}, {"bytes_on_the_wire": "{:,.0f}"}), ""]
    sd = pd.read_csv(R / "sundowning_summary.csv").iloc[0]
    out += ["## Sundowning detector (d >= 0.8, six sittings per part)", "",
            f"- Share of weekly evaluations flagged: {sd.evaluation_flag_rate_sundowner:.0%} for patients with a late-day dip, "
            f"{sd.evaluation_flag_rate_not_sundowner:.1%} for the rest.",
            f"- Patients flagged at least once in the year: {sd.patients_ever_flagged_sundowner:.0%} of those with a dip, "
            f"{sd.patients_ever_flagged_not_sundowner:.0%} of those without.",
            f"- AUC over the effect size: {sd.auc:.2f} ({sd.auc_lo:.2f} to {sd.auc_hi:.2f}).", ""]
    return "\n".join(out)


def main() -> None:
    p = params_from_env()
    started = time.time()
    cohort = get_cohort(p)
    save_table(cohort_summary(cohort), "cohort_summary.csv")
    timings = {}
    for name, step in STEPS:
        t = time.time()
        print(f"\n== {name}")
        step()
        timings[name] = round(time.time() - t, 1)
    (RESULTS / "SUMMARY.md").write_text(summary_md(), encoding="utf-8")
    info = {**run_info(p), "seconds": timings, "total_seconds": round(time.time() - started, 1), "rule_names": RULE_NAMES}
    (RESULTS / "run_info.json").write_text(json.dumps(info, indent=2), encoding="utf-8")
    print(f"\nall done in {info['total_seconds']} s; see {RESULTS / 'SUMMARY.md'}")


if __name__ == "__main__":
    main()
