"""Writes sundowning-vectors.json: sittings in, effect size out, computed by the Python port in
data-science/src/sundowning.py.

backend/.../scoring/SundowningDetector.java (the rule the server runs) is held to this file by
SundowningDetectorTest.sharedVectors, and the Python port is held to it by
data-science/tests/test_sundowning.py, so the version the evaluation measures and the version that runs on the
server cannot drift apart. The inputs are random but seeded; the outputs are unrounded.

    python scripts/make_sundowning_vectors.py
"""
import json
import os
import random
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'data-science', 'src'))

import sundowning  # noqa: E402


def build():
    rng = random.Random(20261009)
    games = ['duck-roll-call', 'family-grove', 'lotus-frog']
    cases = []

    def add(name, sittings, about):
        v = sundowning.evaluate(sittings)
        cases.append({
            'name': name, 'about': about,
            'sittings': [{'gameId': g, 'hour': h, 'score': s} for g, h, s in sittings],
            'expected': {'enoughData': v.enough_data, 'effectSize': v.effect_size,
                         'morning': v.morning, 'lateAfternoon': v.late_afternoon},
        })

    add('too-few', [('a', 9, 80.0)] * 7 + [('a', 17, 60.0)] * 5, 'five afternoon sittings: nothing is said')
    add('identical-scores', [('a', 9, 71.0)] * 6 + [('a', 17, 70.0)] * 6, 'the spread floor of 3 keeps a gap of 1 small')
    add('other-hours-ignored', [('a', 13, 10.0)] * 6 + [('a', 22, 10.0)] * 6, 'midday and night count for neither part')
    add('games-compared-with-themselves', [('hard', 17, 50.0)] * 6 + [('easy', 9, 90.0)] * 6, 'a hard game played only late is not a dip')
    for i in range(14):
        n_m, n_l = rng.randint(4, 14), rng.randint(4, 14)
        dip = rng.choice([0, 0, 3, 6, 10])
        s = []
        for _ in range(n_m):
            s.append((rng.choice(games), rng.choice([6, 7, 8, 9, 10, 11]), round(rng.gauss(65, 9), 1)))
        for _ in range(n_l):
            s.append((rng.choice(games), rng.choice([15, 16, 17, 18, 19]), round(rng.gauss(65 - dip, 9), 1)))
        for _ in range(rng.randint(0, 5)):
            s.append((rng.choice(games), rng.choice([0, 3, 12, 13, 14, 20, 22]), round(rng.gauss(65, 9), 1)))
        rng.shuffle(s)
        add(f'random-{i}', s, f'{n_m} morning and {n_l} late sittings, true dip {dip}')
    return {
        'note': 'Generated by scripts/make_sundowning_vectors.py from data-science/src/sundowning.py. Do not edit by hand.',
        'flagAt': sundowning.FLAG_AT, 'endBelow': sundowning.END_BELOW, 'minPerPart': sundowning.MIN_PER_PART,
        'vectors': cases,
    }


if __name__ == '__main__':
    out = os.path.join(ROOT, 'sundowning-vectors.json')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(build(), f, indent=1)
        f.write('\n')
    print('wrote', out, len(build()['vectors']), 'vectors')
